# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='reporter',
            new_name='user',
        ),
    ]
