# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20160530_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='path',
            field=models.CharField(default='path', max_length=50),
            preserve_default=False,
        ),
    ]
