# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 23:35
from __future__ import unicode_literals

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.upload_location),
        ),
    ]
