# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20160528_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
