# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='user/profile/'),
        ),
    ]
