# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20160604_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user/profile/'),
        ),
    ]
